# Banco de dados H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate DDL Auto (Cria e atualiza tabelas automaticamente para desenvolvimento rápido)
spring.jpa.hibernate.ddl-auto=update

# Console do H2 (Habilitado para dev)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Spring Security - Credenciais para testes locais simples
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER

# Deferir execução do data.sql até que o Hibernate tenha criado a estrutura do banco
spring.jpa.defer-datasource-initialization=true

# Configuração de E-mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testsdeploy@gmail.com
spring.mail.password=ywvh vgkk kxll tkfm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
